name: create_repo
description: sample template

body:
  - type: markdow
    attributes: 
      value: |
        # sample template
        PLease fill the following fields
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true




